#!/usr/bin/env bash

# INSTALLATION GUIDE 
#git config --global mergetool.difftool.cmd 'difftool $BASE $LOCAL $REMOTE'
#git config --global mergetool.difftool.trustExitCode true
# If you want this to become your default mergetool.
#git config --global merge.tool 'difftool'


BASE="$1"
LOCAL="$2"
REMOTE="$3"
diff --color -u "$BASE" "$LOCAL"
diff --color -u "$BASE" "$REMOTE"
exit 1
